### ISSUE TITLE
NTTCP Windows Server 2012 R2 Error - DLL Missing

### ISSUE THREAD

**Issue by destinyrocks** [microsoft/ntttcp#3]
NTTCP when trying to execute on windows server 2012 R2 is encountering the following error :

> "This Program can't start because api-ms-win-core-synch-l1-2-1.dll is missing from your computer. Try reinstalling the program to fix this problem"

![image](https://user-images.githubusercontent.com/5068094/129377053-9c754d98-9903-49b5-8ce7-b8f1fbeb7ebe.png)

**Comment by maolson-msft** [comment]
Hi, which version are you attempting to use? v5.35 was known not to run on old operating systems, but v5.36 added support down to Server 2012.

**Comment by maolson-msft** [comment]
I haven't received a reply, so I'm going to assume v5.36 fixes this issue. Please reopen if that's not the case.
